### ISSUE TITLE
The '%' (mod) operator causes programs to lock up

### ISSUE THREAD

**Issue by rebeccabuckingham** [hth313/Calypsi-tool-chains#17]
Have noticed that when I use the '%' operator, that my program crashes.  I've reproduced this in a small test:

  printf("before trying mod\n");

  int a = 10;

  printf("after assigning a, before b\n");

  int b = a % 9;

  // this line never gets printed
  printf("b is now %d\n", b);

**Comment by hth313** [comment]
There are tests in place that exercises operators so it is likely something else. Do you have ability to use the supplied debugger? You need to enable debug information with the `-g` (or `--debug` ) flag and it makes it possible to test algorithmic stuff. If you have suitable hardware, you may be able to port the remote debugger agent which allows you to also test behavior on hardware.

If this does not help, make a small example project and send it to me, I can try it in the debugger (`db65816).

**Comment by hth313** [comment]
Closing this due to lack of feedback, please reopen this or another ticket with more information if the problem still exists.
