### ISSUE TITLE
M68000: Compiler internal error

### ISSUE THREAD

**Issue by djipi** [hth313/Calypsi-tool-chains#26]
The following message is returned:
"internal error: Translator\Target\M68K\Compiler\FunctionPrelude.hs:(183,11)-(185,74): Non-exhaustive guards in multi-way if"

The error occurs on Release 4.3 and 3.6.12

**Comment by hth313** [comment]
This happen if you allocate a single stack frame larger than 32K. I have fixed this for the upcoming release.

**Comment by hth313** [comment]
This is fixed in the just made 4.4 release.
