### ISSUE TITLE
DWARF version missing information

### ISSUE THREAD

**Issue by djipi** [hth313/Calypsi-tool-chains#28]
This is a minor issue, but it would be good to have, in the document by example, the DWARF version(s) supported by Calypsi.
This information could be useful when developing (or using) debugger in order to take the most from the DWARF version used.

**Comment by hth313** [comment]
The supported version is only DWARF 5. It does not support all aspects of DWARF 5, but enough to support what is currently needed. There are also some vendor extensions used. What in particular are you looking for and what is the intended use?

**Comment by djipi** [comment]
Thank you for the feedback.
I have nothing particular in mind, I'm just a hobbyist and added a debugger in an emulator. Currently using libdwarf library, my debugger handles the DWARDF 2.

**Comment by djipi** [comment]
I have notice, the DWARF version is included now in the documentation. Checked with the Calypsi 5.7 68000 toolchain.
