### ISSUE TITLE
Configuring file stream limits

### ISSUE THREAD

**Issue by KyleCardoza** [hth313/Calypsi-tool-chains#35]
The manual says the following:

> The constant _CONFIG_NFILE_STREAMS found in <nuttx/config.h> defines the number of streams available.

I go into /usr/local/lib/calypsi-65816/src and dig around, but I don't seem to find that file, or any kind of Makefile or the like to rebuild the C library with an increased streams limit. I was wondering what I was missing in how I'm supposed to make use of this.

**Comment by hth313** [comment]
TL;DR; That constant is no more and streams are dynamically allocated.

The library is based on NuttX. The first iteration I used had this constant, a later update made it dynamic and this constant is no more. It will statically allocate the first three streams (stdin, stdout and stderr), the rest are allocated using `malloc()` and kept in a linked list.

**Comment by KyleCardoza** [comment]
Ah. My bad. Either I was reading an outdated version of the manual, or there's a need to update that section. In either case, thank you. 

By the way, did you ever set up a Patreon? If so I'd love to promote it, in addition to subscribing.

**Comment by hth313** [comment]
It had to be updated, which I did for the next release.
I have not set up a Patreon, it is something that I need to ponder more about.
