### ISSUE TITLE
Cannot use gdebi to download the .deb file

### ISSUE THREAD

**Issue by ProxyPlayerHD** [hth313/Calypsi-tool-chains#4]
i've mentioned this once on the 6502 forum, but i still cannot get the gdebi command to work.
i got an Ubuntu VM, updated/upgraded everything, installed gdebi via the `sudo apt install gdebi-core` command mentioned in the user guide, and then tried to run the `sudo gdebi calypsi-nut-3.6.6.deb` command, but all it does is give the "file not found" error.

I assume you're supposed to replace the `nut` in the package name with `65816` (even though the user guide never mentions that, maybe look into that if it should?) but even then i still get the same error.

so what am i missing here? how are you supposed to actually install it from the terminal?
as a work around i've just downloaded the file manually from google drive

**Comment by hth313** [comment]
The `gdebi` command is for installing a local `.deb` file that you have downloaded, it will not fetch it from the server.
If that is not the issues, can you try `which gdebi` and see if it can be found as an executable, maybe it is installed in a directory that is not in your search path.

**Comment by ProxyPlayerHD** [comment]
oooh, well the wording in the user guide makes it sound like it would both download and install it because that's how commands like `apt-get install` or `apt install` usually work.
maybe it should be made a more clearer in the user guide by saying that you first have to download the .deb file manually, and then run the command on it.

**Comment by hth313** [comment]
I will update the user guide to make it more clear. Thank you for pointing it out.
