### ISSUE TITLE
.deb package does not install on Debian Unstable

### ISSUE THREAD

**Issue by KyleCardoza** [hth313/Calypsi-tool-chains#40]
Probably a trivial fix, but the current .deb package for amd64 doesn't install on Debian Unstable, because it requires libtinfo5, while Debian Unstable only offers libtinfo6. I would venture a guess that the easiest fix for this for you would be simply compiling Calypsi for Debian statically, but you'd know better than I.

Thanks!

**Comment by hth313** [comment]
It may be time that I update to a more recent Ubuntu for the build as the current one (20) will reach end of support in April 2025.

While doing that I can see if I can add a dependency to the libtinfoX it happens to use.

**Comment by hth313** [comment]
I have updated the dependency for the coming release 5.7 so that it requests libtinfo6 which is what it actually uses.
