### ISSUE TITLE
Looking for Calypsi's 68000 heap allocation structures information

### ISSUE THREAD

**Issue by djipi** [hth313/Calypsi-tool-chains#49]
In my emulator; I'm adding a feature to display the free and allocated memory spaces using the Calypsi's 68000 library.
I can display the free nodes but still trying to understand better the allocated ones; source code put aside, does there is a document about it?

![image](https://github.com/user-attachments/assets/2b26c880-a764-4ead-a54e-749e0c56fe75)
Example of the free nodes display.

**Comment by hth313** [comment]
I do not think there is any written documentation. It is extracted from NuttX. 
https://github.com/apache/nuttx

**Comment by djipi** [comment]
Thank you for the input and clarification, I believed you created your own structures for the Calypsi's library.
