### ISSUE TITLE
Two subtle math errors

### ISSUE THREAD

**Issue by AwesomeDolphin** [hth313/Calypsi-tool-chains#50]
I found two calculations that render incorrectly.
The first one (tests a and b) seems to skip a division in certain cases, or divide by the wrong thing.
The second one gets some garbage if an int is shifted right till it's 0, and then multiplied.

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <calypsi/intrinsics6502.h>
#include <mega65.h>

void test_a(void) {
    // Incorrect: If abs() used on the right hand side of a /, then the division never happens
    int16_t a = -54;
    int16_t b = a / abs(a);
    printf("A = %d, B = %d\r", a, b);
}

void test_b(void) {
    // Correct: If abs() is stored into a variable, the division happens
    int16_t a = -54;
    int16_t b = abs(a);
    int16_t c = a / b;
    printf("A = %d, B = %d, C = %d\r", a, b, c);
}

void test_c(void) {
    // Incorrect: Shifting x1 by 1, should result in a 0, and 0 times anything is 0
    int x1 = 1;
    int y1 = 0;
    uint32_t addr = 0x50000 + (y1 << 3) + (x1 & 7) + (x1 >> 3) * 64 * 25L;
    printf("ADDR: %08lX\r", addr);
}

void test_d(void) {
    // Correct: Storing the result of the shift gets rid of the spurious calculation of 0xC8
    uint8_t x1 = 1;
    uint8_t y1 = 0;
    uint8_t xshift = x1 >> 3;
    uint32_t addr = 0x50000 + (y1 << 3) + (x1 & 7) + xshift * 64 * 25L;
    printf("ADDR: %08lX\r", addr);
}

void test_entry (void) {
    test_a();
    test_b();
    test_c();
    test_d();
}

**Comment by hth313** [comment]
The first problem is related to spill handling. The second issue is due to incorrect masking done in a rule doing shifts left/right. Both problems have been addressed for the coming release in the next couple of days.

**Comment by hth313** [comment]
5.7.1 is now released with these issues fixed.
