### ISSUE TITLE
68000 compiler miss padding in structures

### ISSUE THREAD

**Issue by djipi** [hth313/Calypsi-tool-chains#53]
Looking at the documentation, there is one mention about padding.
"The 68000 imposes even alignment for data objects larger than one byte. Padding between structure members are used if needed."

The padding in structures are not done in some situations. I have provided a test in the zip file.
[structures.zip](https://github.com/user-attachments/files/17964851/structures.zip)

**Comment by hth313** [comment]
I have fixed this issue for the coming release which will most likely happen in the next couple of days.

**Comment by hth313** [comment]
5.7.1 is now released with this issue fixed.
