### ISSUE TITLE
VSCode debugginging error

### ISSUE THREAD

**Issue by Papakura** [hth313/Calypsi-tool-chains#9]
When trying to debug with VSCode I the following error
![image](https://user-images.githubusercontent.com/2338226/209475232-dc0fb451-f4fb-4053-87a8-229a51d35d50.png)

The debugger seems not to recognize "solib-serach-path" gdb command
VSCode

Version: 1.74.1 (user setup)
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:30:51.966Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

C/C++ for Visual Studio Code V1.13.8
The one mentioned in documentation returns 404

Calypsi debugger for 65816 version 3.6.10

**Comment by hth313** [comment]
You need to remove that from the command line in the launch configuration. There is no need for setting a shared library path, it has no meaning to db65816. The user guide should contain an example you can use as a starting point.

**Comment by Papakura** [comment]
The launch.json does not include anything about shared library. It must the cpptoools debugger host that is calling with that command
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/main.elf",
            "args": ["--logging-enable"],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "miDebuggerPath": "C:/Program Files (x86)/Calypsi-65816/bin/db65816.exe",
            "symbolLoadInfo": {
                "loadAll": false,
                "exceptionList": ""
            }
        }

    ]
}

**Comment by Papakura** [comment]
I get the same thing with the launch.json from the user guide

**Comment by hth313** [comment]
Then they most likely changed the cpp-tools plug-in. You may file a question in that project https://github.com/microsoft/vscode-cpptools 

I may dig into it in the coming days, but as you did not configure it that way, then it is most certainly something they do on their end and the question is if it can be configured not to do it.
